services:
  postgres:
    image: postgres:17-alpine
    container_name: nimbus-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - Postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nimbus-api

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: redis-nimbus
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  Postgres_data:
